### ISSUE TITLE
Android Emulator Issues

### ISSUE THREAD

**Issue by zliving** [zliving/File-Play#18]
After investigating the error `` "Error:trouble processing "java/awt/font/NumericShaper.class":"  ``  is caused by a gradle build error, most likely to do with the android. jar file. This is not because of imported classes like we originally thought. I went through and commented out each standard java import and it didn't fix the error. 

Here are some StackOverflow questions with very little help towards a resolution. 

http://stackoverflow.com/questions/35342485/trouble-processing-java-awt-font-numericshaper-class

http://stackoverflow.com/questions/2387897/cant-generate-apk-because-of-trouble-processing-java-awt-font-numericshaper-cl

http://stackoverflow.com/questions/14989918/error-while-compiling-hello-world-project-for-android-in-intellij-under-ubuntu

I haven't had any success with these solutions. If anyone has time please take a look into investigating this issue. I feel like the more brains the better.

**Comment by jmtaber129** [comment]
Closing because, if I'm not mistaken, this issue was resolved by #20 and #21.
